// This file will be auto-generated by: npm run db:generate-types
// For now, we'll create basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          username: string
          full_name: string | null
          avatar_url: string | null
          plan_type: 'free' | 'pro' | 'enterprise'
          api_keys: Json
          usage_limits: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username: string
          full_name?: string | null
          avatar_url?: string | null
          plan_type?: 'free' | 'pro' | 'enterprise'
          api_keys?: Json
          usage_limits?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string
          full_name?: string | null
          avatar_url?: string | null
          plan_type?: 'free' | 'pro' | 'enterprise'
          api_keys?: Json
          usage_limits?: Json
          created_at?: string
          updated_at?: string
        }
      }
      agents: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          system_prompt: string
          capabilities: string[]
          model: string
          temperature: number
          max_tokens: number
          tools: Json
          knowledge_base: Json
          icon: string
          color: string
          is_public: boolean
          marketplace_category: string | null
          downloads_count: number
          rating: number | null
          version: string
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          system_prompt: string
          capabilities?: string[]
          model?: string
          temperature?: number
          max_tokens?: number
          tools?: Json
          knowledge_base?: Json
          icon?: string
          color?: string
          is_public?: boolean
          marketplace_category?: string | null
          downloads_count?: number
          rating?: number | null
          version?: string
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          description?: string | null
          system_prompt?: string
          capabilities?: string[]
          model?: string
          temperature?: number
          max_tokens?: number
          tools?: Json
          knowledge_base?: Json
          icon?: string
          color?: string
          is_public?: boolean
          marketplace_category?: string | null
          downloads_count?: number
          rating?: number | null
          version?: string
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      workflows: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          trigger_type: string
          trigger_config: Json
          steps: Json
          is_active: boolean
          is_public: boolean
          marketplace_category: string | null
          downloads_count: number
          rating: number | null
          version: string
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          trigger_type?: string
          trigger_config?: Json
          steps?: Json
          is_active?: boolean
          is_public?: boolean
          marketplace_category?: string | null
          downloads_count?: number
          rating?: number | null
          version?: string
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          description?: string | null
          trigger_type?: string
          trigger_config?: Json
          steps?: Json
          is_active?: boolean
          is_public?: boolean
          marketplace_category?: string | null
          downloads_count?: number
          rating?: number | null
          version?: string
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      executions: {
        Row: {
          id: string
          user_id: string
          workflow_id: string | null
          agent_id: string | null
          status: string
          input: string | null
          output: string | null
          steps_completed: number
          steps_total: number
          current_step: Json | null
          error_message: string | null
          duration_ms: number | null
          tokens_used: number
          cost_usd: number
          metadata: Json
          started_at: string | null
          completed_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          workflow_id?: string | null
          agent_id?: string | null
          status?: string
          input?: string | null
          output?: string | null
          steps_completed?: number
          steps_total?: number
          current_step?: Json | null
          error_message?: string | null
          duration_ms?: number | null
          tokens_used?: number
          cost_usd?: number
          metadata?: Json
          started_at?: string | null
          completed_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          workflow_id?: string | null
          agent_id?: string | null
          status?: string
          input?: string | null
          output?: string | null
          steps_completed?: number
          steps_total?: number
          current_step?: Json | null
          error_message?: string | null
          duration_ms?: number | null
          tokens_used?: number
          cost_usd?: number
          metadata?: Json
          started_at?: string | null
          completed_at?: string | null
          created_at?: string
        }
      }
      marketplace_items: {
        Row: {
          id: string
          item_type: 'agent' | 'workflow'
          item_id: string
          author_id: string
          title: string
          description: string | null
          category: string
          tags: string[]
          price: number
          downloads: number
          rating: number | null
          reviews_count: number
          featured: boolean
          verified: boolean
          version: string
          changelog: string | null
          screenshots: string[]
          demo_video_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          item_type: 'agent' | 'workflow'
          item_id: string
          author_id: string
          title: string
          description?: string | null
          category: string
          tags?: string[]
          price?: number
          downloads?: number
          rating?: number | null
          reviews_count?: number
          featured?: boolean
          verified?: boolean
          version?: string
          changelog?: string | null
          screenshots?: string[]
          demo_video_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          item_type?: 'agent' | 'workflow'
          item_id?: string
          author_id?: string
          title?: string
          description?: string | null
          category?: string
          tags?: string[]
          price?: number
          downloads?: number
          rating?: number | null
          reviews_count?: number
          featured?: boolean
          verified?: boolean
          version?: string
          changelog?: string | null
          screenshots?: string[]
          demo_video_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      reviews: {
        Row: {
          id: string
          marketplace_item_id: string
          user_id: string
          rating: number
          comment: string | null
          helpful_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          marketplace_item_id: string
          user_id: string
          rating: number
          comment?: string | null
          helpful_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          marketplace_item_id?: string
          user_id?: string
          rating?: number
          comment?: string | null
          helpful_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      analytics_events: {
        Row: {
          id: string
          user_id: string
          execution_id: string | null
          event_type: string
          agent_id: string | null
          workflow_id: string | null
          duration_ms: number | null
          tokens_used: number | null
          cost_usd: number | null
          success: boolean | null
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          execution_id?: string | null
          event_type: string
          agent_id?: string | null
          workflow_id?: string | null
          duration_ms?: number | null
          tokens_used?: number | null
          cost_usd?: number | null
          success?: boolean | null
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          execution_id?: string | null
          event_type?: string
          agent_id?: string | null
          workflow_id?: string | null
          duration_ms?: number | null
          tokens_used?: number | null
          cost_usd?: number | null
          success?: boolean | null
          metadata?: Json
          created_at?: string
        }
      }
      api_keys: {
        Row: {
          id: string
          user_id: string
          key_hash: string
          name: string
          last_used_at: string | null
          usage_count: number
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          key_hash: string
          name: string
          last_used_at?: string | null
          usage_count?: number
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          key_hash?: string
          name?: string
          last_used_at?: string | null
          usage_count?: number
          is_active?: boolean
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      validate_api_key: {
        Args: { key_hash_param: string }
        Returns: { user_id: string; is_valid: boolean }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
